In [5]:
import numpy as np

def solve_variant(A, B, C, variant_number):
    print(f"ВАРИАНТ {variant_number}")
    
    print("Матрица A:")
    print(A)
    print("\nМатрица B:")
    print(B)
    print("\nМатрица C:")
    print(C)
    
    A_plus_B = A + B
    print("\n1. A + B =")
    print(A_plus_B)
    
    B_minus_A = B - A
    print("\n2. B - A =")
    print(B_minus_A)
    
    A_times_C = np.dot(A, C)
    print("\n3. A * C =")
    print(A_times_C)
    
    A_times_B = np.dot(A, B)
    A_times_B_times_C = np.dot(A_times_B, C)
    print("\n4. A * B * C =")
    print(A_times_B_times_C)
    
    return A_plus_B, B_minus_A, A_times_C, A_times_B_times_C

A1 = np.array([[1, 2, 4], [7, 5, -2], [-2, 1, 3]])
B1 = np.array([[-1, 0, 3], [2, -6, 1], [-7, 1, 5]])
C1 = np.array([[-2, 3], [4, 0], [7, -1]])

A2 = np.array([[0, 3, 4], [-7, 1, -2], [2, -1, 3]])
B2 = np.array([[1, 2, 4], [7, 0, -2], [-3, -2, 5]])
C2 = np.array([[-3, 2], [0, 4], [-1, 7]])

result1 = solve_variant(A1, B1, C1, 1)
result2 = solve_variant(A2, B2, C2, 2)


ВАРИАНТ 1
Матрица A:
[[ 1  2  4]
 [ 7  5 -2]
 [-2  1  3]]

Матрица B:
[[-1  0  3]
 [ 2 -6  1]
 [-7  1  5]]

Матрица C:
[[-2  3]
 [ 4  0]
 [ 7 -1]]

1. A + B =
[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]

2. B - A =
[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]

3. A * C =
[[34 -1]
 [-8 23]
 [29 -9]]

4. A * B * C =
[[ 193 -100]
 [ -50   35]
 [  92  -61]]
ВАРИАНТ 2
Матрица A:
[[ 0  3  4]
 [-7  1 -2]
 [ 2 -1  3]]

Матрица B:
[[ 1  2  4]
 [ 7  0 -2]
 [-3 -2  5]]

Матрица C:
[[-3  2]
 [ 0  4]
 [-1  7]]

1. A + B =
[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]

2. B - A =
[[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]

3. A * C =
[[ -4  40]
 [ 23 -24]
 [ -9  21]]

4. A * B * C =
[[ -41   84]
 [  22 -308]
 [  17  139]]
